<?php

return [
    /*
     * Key harus berupa hasil normalisasi jenis surat:
     * huruf kecil dan hanya karakter a-z/0-9.
     */
    'documents' => [
        'suratpernyataanmengizinkanikutkk' => [
            'label' => 'Surat Pernyataan Mengizinkan Ikut KK',
            'model' => \App\Models\surat_pernyataan_mengizinkan_ikut_kk::class,
            'view' => 'surat.pdf_pernyataan_mengizinkan_ikut_kk',
            'filename_prefix' => 'surat_pernyataan_mengizinkan_ikut_kk',
            'filename_fields' => ['nama'],
            'aliases' => ['pernyataan_mengizinkan_ikut_kk_suami_istri_keluarga'],
        ],
        'suratpernyataanpembetulandatatidakmerubahlagi' => [
            'label' => 'Surat Pernyataan Pembetulan Data',
            'model' => \App\Models\surat_pernyataan_pembetulan_data_tidak_merubah_lagi::class,
            'view' => 'surat.pdf_pernyataan_pembetulan_data_tidak_merubah_lagi',
            'filename_prefix' => 'surat_pernyataan_pembetulan_data',
            'filename_fields' => ['nama'],
            'aliases' => ['pernyataan_pembetulan_data_tidak_merubah_lagi'],
        ],
        'suratpernyataanperubahandatapendidikan' => [
            'label' => 'Surat Pernyataan Perubahan Data Pendidikan',
            'model' => \App\Models\surat_pernyataan_perubahan_data_pendidikan::class,
            'view' => 'surat.pdf_pernyataan_perubahan_data_pendidikan',
            'filename_prefix' => 'surat_pernyataan_perubahan_data_pendidikan',
            'filename_fields' => ['nama'],
            'aliases' => ['pernyataan_perubahan_data_pendidikan'],
        ],
        'suratrekomendasibbm' => [
            'label' => 'Surat Rekomendasi BBM',
            'model' => \App\Models\SuratRekomendasiBbm::class,
            'view' => 'surat.pdf_rekomendasi_bbm',
            'filename_prefix' => 'surat_rekomendasi_bbm',
            'filename_fields' => ['nama_lengkap'],
            'aliases' => ['surat_rekomendasi_bbm', 'rekomendasi_bbm'],
        ],
        'suratpengantarskck' => [
            'label' => 'Surat Pengantar SKCK',
            'model' => \App\Models\SuratPengantarSkck::class,
            'view' => 'surat.pdf_skck',
            'filename_prefix' => 'surat_pengantar_skck',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_pengantar_skck', 'skck'],
        ],
        'sptjmkematian' => [
            'label' => 'SPTJM Kematian',
            'model' => \App\Models\surat_sptjm_kematian::class,
            'view' => 'surat.pdf_sptjm_kematian',
            'filename_prefix' => 'sptjm_kematian',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_sptjm_kematian'],
        ],
        'suratformulirpengajuanuserid' => [
            'label' => 'Formulir Pengajuan User ID',
            'model' => \App\Models\surat_formulir_pengajuan_user_id::class,
            'view' => 'surat.pdf_surat_formulir_pengajuan_user_id',
            'filename_prefix' => 'formulir_pengajuan_user_id',
            'filename_fields' => ['instansi_pemohon', 'nama_pemohon'],
            'aliases' => ['surat_formulir_pengajuan_user_id', 'formulir_pengajuan_user_id'],
        ],
        'suratijinkeluarga' => [
            'label' => 'Surat Izin Keluarga',
            'model' => \App\Models\SuratIjinKeluarga::class,
            'view' => 'surat.pdf_surat_ijin_keluarga',
            'filename_prefix' => 'surat_ijin_keluarga',
            'filename_fields' => ['nama_suami', 'nama_istri'],
            'aliases' => ['surat_ijin_keluarga', 'ijin_keluarga', 'suratizinkeluarga'],
        ],
        'suratketeranganahliwaris' => [
            'label' => 'Surat Keterangan Ahli Waris',
            'model' => \App\Models\surat_keterangan_ahli_waris::class,
            'view' => 'surat.pdf_surat_keterangan_ahli_waris',
            'filename_prefix' => 'surat_keterangan_ahli_waris',
            'filename_fields' => ['nama_lengkap'],
            'aliases' => ['surat_keterangan_ahli_waris', 'ahli_waris'],
        ],
        'suratketerangandesamiskin' => [
            'label' => 'Surat Keterangan Desa Miskin',
            'model' => \App\Models\SuratKeteranganDesaMiskin::class,
            'view' => 'surat.pdf_surat_keterangan_desa_miskin',
            'filename_prefix' => 'surat_keterangan_desa_miskin',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_keterangan_desa_miskin', 'miskindesa'],
        ],
        'suratketerangandesapernahmenikah' => [
            'label' => 'Surat Keterangan Desa Pernah Menikah',
            'model' => \App\Models\surat_keterangan_desa_pernah_menikah::class,
            'view' => 'surat.pdf_surat_keterangan_desa_pernah_menikah',
            'filename_prefix' => 'surat_keterangan_desa_pernah_menikah',
            'filename_fields' => ['nama_lengkap'],
            'aliases' => ['surat_keterangan_desa_pernah_menikah'],
        ],
        'suratketerangandesasebagaipenduduk' => [
            'label' => 'Surat Keterangan Desa sebagai Penduduk',
            'model' => \App\Models\SuratKeteranganDesaSebagaiPenduduk::class,
            'view' => 'surat.pdf_surat_keterangan_desa_sebagai_penduduk',
            'filename_prefix' => 'surat_keterangan_desa_sebagai_penduduk',
            'filename_fields' => ['nama_lengkap'],
            'aliases' => ['surat_keterangan_desa_sebagai_penduduk', 'desa_penduduk'],
        ],
        'suratketerangandomisililembaga' => [
            'label' => 'Surat Keterangan Domisili Lembaga',
            'model' => \App\Models\SuratKeteranganDomisiliLembaga::class,
            'view' => 'surat.pdf_surat_keterangan_domisili_lembaga',
            'filename_prefix' => 'surat_keterangan_domisili_lembaga',
            'filename_fields' => ['nama_lembaga', 'nama_pengurus'],
            'aliases' => ['surat_keterangan_domisili_lembaga', 'domisili_lembaga'],
        ],
        'suratketerangandomisiliwarga' => [
            'label' => 'Surat Keterangan Domisili Warga',
            'model' => \App\Models\SuratKeteranganDomisiliWarga::class,
            'view' => 'surat.pdf_surat_keterangan_domisili_warga',
            'filename_prefix' => 'surat_keterangan_domisili_warga',
            'filename_fields' => ['nama_lengkap'],
            'aliases' => ['surat_keterangan_domisili_warga', 'domisili_warga'],
        ],
        'suratketeranganghoib' => [
            'label' => 'Surat Keterangan Ghoib',
            'model' => \App\Models\surat_keterangan_ghoib::class,
            'view' => 'surat.pdf_surat_keterangan_ghoib',
            'filename_prefix' => 'surat_keterangan_ghoib',
            'filename_fields' => ['nama_pemohon'],
            'aliases' => ['surat_keterangan_ghoib', 'ghoib'],
        ],
        'suratketeranganhargakepemilikantanah' => [
            'label' => 'Surat Keterangan Harga Kepemilikan Tanah',
            'model' => \App\Models\surat_keterangan_harga_kepemilikan_tanah::class,
            'view' => 'surat.pdf_surat_keterangan_harga_kepemilikan_tanah',
            'filename_prefix' => 'surat_keterangan_harga_kepemilikan_tanah',
            'filename_fields' => ['atas_nama_hak_milik', 'atas_nama'],
            'aliases' => ['surat_keterangan_harga_kepemilikan_tanah'],
        ],
        'suratketerangankematiandesa' => [
            'label' => 'Surat Keterangan Kematian Desa',
            'model' => \App\Models\surat_keterangan_kematian_desa::class,
            'view' => 'surat.pdf_surat_keterangan_kematian_desa',
            'filename_prefix' => 'surat_keterangan_kematian_desa',
            'filename_fields' => ['nama_lengkap'],
            'aliases' => ['surat_keterangan_kematian_desa', 'kematian_desa'],
        ],
        'suratketerangankepemilikanaset' => [
            'label' => 'Surat Keterangan Kepemilikan Aset',
            'model' => \App\Models\SuratKeteranganKepemilikanAset::class,
            'view' => 'surat.pdf_surat_keterangan_kepemilikan_aset',
            'filename_prefix' => 'surat_keterangan_kepemilikan_aset',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_keterangan_kepemilikan_aset', 'kepemilikan_aset'],
        ],
        'suratketeranganmiskinskm' => [
            'label' => 'Surat Keterangan Miskin SKM',
            'model' => \App\Models\SuratKeteranganMiskinSkm::class,
            'view' => 'surat.pdf_surat_keterangan_miskin_skm',
            'filename_prefix' => 'surat_keterangan_miskin_skm',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_keterangan_miskin_skm', 'skm'],
        ],
        'suratketerangannumpangnikah' => [
            'label' => 'Surat Keterangan Numpang Nikah',
            'model' => \App\Models\surat_keterangan_numpang_nikah::class,
            'view' => 'surat.pdf_surat_keterangan_numpang_nikah',
            'filename_prefix' => 'surat_keterangan_numpang_nikah',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_keterangan_numpang_nikah', 'numpang_nikah'],
        ],
        'suratketeranganpenghasilan' => [
            'label' => 'Surat Keterangan Penghasilan',
            'model' => \App\Models\surat_keterangan_penghasilan::class,
            'view' => 'surat.pdf_surat_keterangan_penghasilan',
            'filename_prefix' => 'surat_keterangan_penghasilan',
            'filename_fields' => ['nama_lengkap'],
            'aliases' => ['surat_keterangan_penghasilan', 'penghasilan'],
        ],
        'suratketerangantidakmampu' => [
            'label' => 'Surat Keterangan Tidak Mampu',
            'model' => \App\Models\suratketerangantidakmampu::class,
            'view' => 'surat.pdf_surat_keterangan_tidakmampu',
            'filename_prefix' => 'surat_keterangan_tidak_mampu',
            'filename_fields' => ['nama_lengkap', 'nama_pelapor'],
            'aliases' => ['surat_keterangan_tidakmampu', 'surat_keterangan_tidak_mampu', 'tidakmampu'],
        ],
        'suratketeranganusaha' => [
            'label' => 'Surat Keterangan Usaha',
            'model' => \App\Models\SuratKeteranganUsaha::class,
            'view' => 'surat.pdf_surat_keterangan_usaha',
            'filename_prefix' => 'surat_keterangan_usaha',
            'filename_fields' => ['nama', 'nama_usaha'],
            'aliases' => ['surat_keterangan_usaha', 'usaha'],
        ],
        'suratkuasa' => [
            'label' => 'Surat Kuasa',
            'model' => \App\Models\SuratKuasa::class,
            'view' => 'surat.pdf_surat_kuasa',
            'filename_prefix' => 'surat_kuasa',
            'filename_fields' => ['nama_pihak1', 'p1_nama_lengkap'],
            'aliases' => ['surat_kuasa', 'kuasa'],
        ],
        'suratnotaangkutan' => [
            'label' => 'Surat Nota Angkutan',
            'model' => \App\Models\SuratNotaAngkutan::class,
            'view' => 'surat.pdf_surat_nota_angkutan',
            'filename_prefix' => 'surat_nota_angkutan',
            'filename_fields' => ['nama_pengirim'],
            'aliases' => ['surat_nota_angkutan', 'nota_angkutan'],
        ],
        'suratperintahperjalanandinas' => [
            'label' => 'Surat Perintah Perjalanan Dinas',
            'model' => \App\Models\SuratPerintahPerjalananDinas::class,
            'view' => 'surat.pdf_surat_perintah_perjalanan_dinas',
            'filename_prefix' => 'surat_perintah_perjalanan_dinas',
            'filename_fields' => ['nama_pegawai'],
            'aliases' => ['surat_perintah_perjalanan_dinas', 'perintah_perjalanan_dinas', 'sppd'],
        ],
        'suratperintahtugas' => [
            'label' => 'Surat Perintah Tugas',
            'model' => \App\Models\SuratPerintahTugas::class,
            'view' => 'surat.pdf_surat_perintah_tugas',
            'filename_prefix' => 'surat_perintah_tugas',
            'filename_fields' => ['penerima_tugas.0.nama', 'nama_penerima'],
            'aliases' => ['surat_perintah_tugas', 'perintah_tugas'],
        ],
        'permohonanpembukaanrekening' => [
            'label' => 'Permohonan Pembukaan Rekening',
            'model' => \App\Models\SuratPermohonanPembukaanRekening::class,
            'view' => 'surat.pdf_surat_permohonan_pembukaan_rekening',
            'filename_prefix' => 'surat_permohonan_pembukaan_rekening',
            'filename_fields' => ['nama_kepala_desa', 'ybt_nama'],
            'aliases' => ['surat_permohonan_pembukaan_rekening', 'suratpermohonanpembukaanrekening', 'bukaanrekening'],
        ],
        'suratpermohonanpengantarkeabsahanaktakelahiran' => [
            'label' => 'Permohonan Pengantar Keabsahan Akta Kelahiran',
            'model' => \App\Models\surat_permohonan_pengantar_keabsahan_akta_kelahiran::class,
            'view' => 'surat.pdf_surat_permohonan_pengantar_keabsahan_akta_kelahiran',
            'filename_prefix' => 'surat_permohonan_pengantar_keabsahan_akta_kelahiran',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_permohonan_pengantar_keabsahan_akta_kelahiran', 'permohonan_pengantar_keabsahan_akta_kelahiran'],
        ],
        'suratpermohonanpengantarkeabsahanaktakelahirananak' => [
            'label' => 'Permohonan Pengantar Keabsahan Akta Kelahiran Anak',
            'model' => \App\Models\surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak::class,
            'view' => 'surat.pdf_surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak',
            'filename_prefix' => 'surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak',
            'filename_fields' => ['nama_anak', 'nama'],
            'aliases' => ['surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak', 'permohonan_pengantar_keabsahan_akta_kelahiran_anak'],
        ],
        'suratpernyataanbatalpindahpenduduk' => [
            'label' => 'Surat Pernyataan Batal Pindah Penduduk',
            'model' => \App\Models\surat_pernyataan_batal_pindah_penduduk::class,
            'view' => 'surat.pdf_surat_pernyataan_batal_pindah_penduduk',
            'filename_prefix' => 'surat_pernyataan_batal_pindah_penduduk',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_pernyataan_batal_pindah_penduduk', 'pernyataan_batal_pindah_penduduk'],
        ],
        'suratpernyataanbelumakta' => [
            'label' => 'Surat Pernyataan Belum Akta',
            'model' => \App\Models\surat_pernyataan_belum_akta::class,
            'view' => 'surat.pdf_surat_pernyataan_belum_akta',
            'filename_prefix' => 'surat_pernyataan_belum_akta',
            'filename_fields' => ['ybt_nama', 'subjek_nama'],
            'aliases' => ['surat_pernyataan_belum_akta'],
        ],
        'suratpernyataandanjaminan' => [
            'label' => 'Surat Pernyataan dan Jaminan',
            'model' => \App\Models\surat_pernyataan_dan_jaminan::class,
            'view' => 'surat.pdf_surat_pernyataan_dan_jaminan',
            'filename_prefix' => 'surat_pernyataan_dan_jaminan',
            'filename_fields' => ['nama_pembuat'],
            'aliases' => ['surat_pernyataan_dan_jaminan'],
        ],
        'suratpernyataankepemilikandokumenasli' => [
            'label' => 'Surat Pernyataan Kepemilikan Dokumen Asli',
            'model' => \App\Models\SuratPernyataanKepemilikanDokumenAsli::class,
            'view' => 'surat.pdf_surat_pernyataan_kepemilikan_dokumen_asli',
            'filename_prefix' => 'surat_pernyataan_kepemilikan_dokumen_asli',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_pernyataan_kepemilikan_dokumen_asli', 'pernyataan_kepemilikan_dokumen'],
        ],
        'suratpernyataankesanggupan' => [
            'label' => 'Surat Pernyataan Kesanggupan',
            'model' => \App\Models\SuratPernyataanKesanggupan::class,
            'view' => 'surat.pdf_surat_pernyataan_kesanggupan',
            'filename_prefix' => 'surat_pernyataan_kesanggupan',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_pernyataan_kesanggupan', 'pernyataan_kesanggupan', 'kesanggupan'],
        ],
        'suratpernyataanmemilihnamaalias' => [
            'label' => 'Surat Pernyataan Memilih Nama Alias',
            'model' => \App\Models\surat_pernyataan_memilih_nama_alias::class,
            'view' => 'surat.pdf_surat_pernyataan_memilih_nama_alias',
            'filename_prefix' => 'surat_pernyataan_memilih_nama_alias',
            'filename_fields' => ['nama_pemilih', 'nama'],
            'aliases' => ['surat_pernyataan_memilih_nama_alias'],
        ],
        'suratpernyataanmemilihnamaaliassatuorangtua' => [
            'label' => 'Surat Pernyataan Memilih Nama Alias Satu Orang Tua',
            'model' => \App\Models\nama_alias_ortu::class,
            'view' => 'surat.pdf_surat_pernyataan_memilih_nama_alias_satu_ortu',
            'filename_prefix' => 'surat_pernyataan_memilih_nama_alias_satu_orang_tua',
            'filename_fields' => ['nama_menyatakan', 'nama'],
            'aliases' => ['surat_pernyataan_memilih_nama_alias_satu_orang_tua', 'surat_pernyataan_memilih_nama_alias_satu_ortu'],
        ],
        'suratpernyataanmiskin' => [
            'label' => 'Surat Pernyataan Miskin',
            'model' => \App\Models\SuratPernyataanMiskin::class,
            'view' => 'surat.pdf_surat_pernyataan_miskin',
            'filename_prefix' => 'surat_pernyataan_miskin',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_pernyataan_miskin', 'pernyataan_miskin'],
        ],
        'suratpernyataantidakpunyakartujkn' => [
            'label' => 'Surat Pernyataan Tidak Punya Kartu JKN',
            'model' => \App\Models\SuratPernyataanTidakPunyaKartuJkn::class,
            'view' => 'surat.pdf_surat_pernyataan_tidak_punya_kartu_jkn',
            'filename_prefix' => 'surat_pernyataan_tidak_punya_kartu_jkn',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_pernyataan_tidak_punya_kartu_jkn', 'pernyataan_tidak_punya_kartu_jkn', 'jamkesmas', 'jkn'],
        ],
        'suratrekomendasi' => [
            'label' => 'Surat Rekomendasi',
            'model' => \App\Models\SuratRekomendasi::class,
            'view' => 'surat.pdf_surat_rekomendasi',
            'filename_prefix' => 'surat_rekomendasi',
            'filename_fields' => ['nama', 'perihal'],
            'aliases' => ['surat_rekomendasi', 'rekomendasi'],
        ],
        'suratsptjmsuamiistri' => [
            'label' => 'SPTJM Suami Istri',
            'model' => \App\Models\surat_sptjm_suami_istri::class,
            'view' => 'surat.pdf_surat_sptjm_suami_istri',
            'filename_prefix' => 'sptjm_suami_istri',
            'filename_fields' => ['nama_deklaran'],
            'aliases' => ['surat_sptjm_suami_istri', 'sptjm_suami_istri'],
        ],
        'suratundangan' => [
            'label' => 'Surat Undangan',
            'model' => \App\Models\SuratUndangan::class,
            'view' => 'surat.pdf_surat_undangan',
            'filename_prefix' => 'surat_undangan',
            'filename_fields' => ['perihal', 'kepada_yth'],
            'aliases' => ['surat_undangan', 'undangan'],
        ],
        'suratketerangankehilangan' => [
            'label' => 'Surat Keterangan Kehilangan',
            'model' => \App\Models\surat_keterangan_kehilangan::class,
            'view' => 'surat.pdfsuratketerangankehilangan',
            'filename_prefix' => 'surat_keterangan_kehilangan',
            'filename_fields' => ['nama_pelapor'],
            'aliases' => ['surat_keterangan_kehilangan'],
        ],
        'suratpernyataannumpangkk' => [
            'label' => 'Surat Pernyataan Numpang KK',
            'model' => \App\Models\surat_pernyataan_numpang_kk::class,
            'view' => 'surat.pdfsuratnumpangkk',
            'filename_prefix' => 'surat_pernyataan_numpang_kk',
            'filename_fields' => ['nama_pemilik_kk', 'nama_penumpang_kk'],
            'aliases' => ['surat_pernyataan_numpang_kk'],
        ],
        'suratpernyataantidakbisamelampirkanktpkematian' => [
            'label' => 'Surat Pernyataan Tidak Bisa Melampirkan KTP Kematian',
            'model' => \App\Models\surat_pernyataan_tidak_bisa_melampirkan_ktp_kematian::class,
            'view' => 'surat.pdfsuratpernyataantidakbisamelampirkanktpkematian',
            'filename_prefix' => 'surat_pernyataan_tidak_bisa_melampirkan_ktp_kematian',
            'filename_fields' => ['nama_pelapor'],
            'aliases' => ['surat_pernyataan_tidak_bisa_melampirkan_ktp_kematian'],
        ],
        'suratketeranganahliwarisdesa' => [
            'label' => 'Surat Keterangan Ahli Waris Desa',
            'model' => \App\Models\surat_keterangan_ahli_waris_desa::class,
            'view' => 'surat.pdf_ahli_waris_desa',
            'filename_prefix' => 'surat_keterangan_ahli_waris_desa',
            'filename_fields' => ['nama_almarhum'],
            'aliases' => ['surat_keterangan_ahli_waris_desa', 'ahliwarisdesa'],
        ],
        'suratpermohonanpernyataanmiskin' => [
            'label' => 'Surat Permohonan Pernyataan Miskin',
            'model' => \App\Models\SuratPermohonanPernyataanMiskin::class,
            'view' => 'surat.pdf_permohonan_pernyataan_miskin',
            'filename_prefix' => 'surat_permohonan_pernyataan_miskin',
            'filename_fields' => ['nama_pasien'],
            'aliases' => ['surat_permohonan_pernyataan_miskin', 'permohonan_pernyataan_miskin'],
        ],
        'suratpermohonantebangpohon' => [
            'label' => 'Surat Permohonan Tebang Pohon',
            'model' => \App\Models\SuratPermohonanTebangPohon::class,
            'view' => 'surat.pdf_permohonan_tebang_pohon',
            'filename_prefix' => 'surat_permohonan_tebang_pohon',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_permohonan_tebang_pohon', 'permohonan_tebang_pohon', 'tebangpohon'],
        ],
        'suratpernyataanaktabarcodenomorsama' => [
            'label' => 'Surat Pernyataan Akta Barcode Nomor Sama',
            'model' => \App\Models\surat_pernyataan_akta_barcode_nomor_sama::class,
            'view' => 'surat.pdf_pernyataan_akta_barcode_nomor_sama',
            'filename_prefix' => 'surat_pernyataan_akta_barcode_nomor_sama',
            'filename_fields' => ['nama', 'nama_pemohon'],
            'aliases' => ['surat_pernyataan_akta_barcode_nomor_sama'],
        ],
        'suratpernyataananakseorangnamaibu' => [
            'label' => 'Surat Pernyataan Anak Seorang Nama Ibu',
            'model' => \App\Models\surat_pernyataan_anak_seorang_nama_ibu::class,
            'view' => 'surat.pdf_pernyataan_anak_seorang_nama_ibu',
            'filename_prefix' => 'surat_pernyataan_anak_seorang_nama_ibu',
            'filename_fields' => ['nama', 'nama_anak'],
            'aliases' => ['surat_pernyataan_anak_seorang_nama_ibu'],
        ],
        'suratpernyataanbedanamabukunikah' => [
            'label' => 'Surat Pernyataan Beda Nama Buku Nikah',
            'model' => \App\Models\surat_pernyataan_beda_nama_buku_nikah::class,
            'view' => 'surat.pdf_pernyataan_beda_nama_buku_nikah',
            'filename_prefix' => 'surat_pernyataan_beda_nama_buku_nikah',
            'filename_fields' => ['nama'],
            'aliases' => ['surat_pernyataan_beda_nama_buku_nikah'],
        ],
    ],
];
